export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const LOAD_WALLET_SUCCESS = "LOAD_WALLET_SUCCESS";
export const SEND_MONEY_SUCCESS = "SEND_MONEY_SUCCESS";
export const REQUEST_MONEY_SUCCESS = "REQUEST_MONEY_SUCCESS";
